import type { Metadata } from "next";
import { HeaderBlog } from "../components/HeaderBlog";
import { Footer } from "../components/blog/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <HeaderBlog />
      <main className="mt-[130px]">{children}</main>
      <Footer />
    </div>
  );
}
